///////////////////////////////////////////////////////
// VAC350Indices.h
//
//
// M.McKiernan									03-06-2003
// First pass.
//*****************************************************************************
// MACROS
//*****************************************************************************
#ifndef __VAC350INDICES_H__
#define __VAC350INDICES_H__


// VAC350

#define	VAC350_MAX_LOADERS		32		// max no. of loaders (*******FOR MVS COMPATIBILITY******)

#define   MB_VAC350_CALBLOCKSIZE    8		// SIZE OF CALIB BLOCK FOR EACH LOADER



// FAST STATUS READ
// Unused in the VAC350

// CALIBRATION DATA

#define   MB_VAC350_NOOFLOADERS              0
#define   MB_VAC350_NOOFPUMPS                1
#define   MB_VAC350_CENTRALFILTER            2
#define   MB_VAC350_PUMPIDLETIME             3	// IDLE TIME IN L.S. BYTE
#define   MB_VAC350_ATMVALEIDLETIME          4	// FILL ON TO AV OFF TIME
#define   MB_VAC350_DUMPDELAY                5	// TIME TO DUMP RESERVOIR
#define   MB_VAC350_CALSPARE1                6

// Offsets into calibration block.
#define   MB_ADDRESS_OFFSET               0
#define   MB_PUMPNO_OFFSET                1   // NO. OF PUMP FOR THIS LOADER
#define   MB_ID_OFFSET                    2   // ID FOR THIS LOADER
#define   MB_PRIORITY_OFFSET              4   // PRIORITY(1-7) FOR THIS LOADER
#define   MB_SUCTIONTIME_OFFSET           5   // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_PREPOST_OFFSET               6   // PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_SPARE_OFFSET                 7   // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 1
#define   MB_VAC350_CALBLOCK_L1			10    //CALIB. BLOCK FOR LOADER 1

#define   MB_VAC350_ADDRESS_L1               MB_VAC350_CALBLOCK_L1 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L1                MB_VAC350_CALBLOCK_L1 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L1               	MB_VAC350_CALBLOCK_L1 + MB_ID_OFFSET	// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L1               	MB_VAC350_CALBLOCK_L1 + MB_ID_OFFSET+1	// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L1              MB_VAC350_CALBLOCK_L1 + MB_PRIORITY_OFFSET	// PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L1           MB_VAC350_CALBLOCK_L1 + MB_SUCTIONTIME_OFFSET	// SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L1               MB_VAC350_CALBLOCK_L1 + MB_PREPOST_OFFSET	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L1                 MB_VAC350_CALBLOCK_L1 + MB_SPARE_OFFSET	// SPARE REGISTER FOR THIS LOADER

//#define   MB_VAC350_ADDRESS_L1               10
//#define   MB_VAC350_PUMPNO_L1                11	// NO. OF PUMP FOR THIS LOADER
//#define   MB_VAC350_ID_L1               	12	// ID FOR THIS LOADER
//#define   MB_VAC350_IDLSW_L1               	13	// ID L.S.WORD FOR THIS LOADER
//#define   MB_VAC350_PRIORITY_L1              14	// PRIORITY(1-7) FOR THIS LOADER
//#define   MB_VAC350_SUCTIONTIME_L1           15	// SUCTION TIME SECS (MAX 255) FOR THIS LOADER
//#define   MB_VAC350_PREPOST_L1               16	// PRE-POST FILL TIMES FOR THIS LOADER
//#define   MB_VAC350_SPARE_L1                 17	// SPARE REGISTER FOR THIS LOADER
//#define   MB_VAC350_CALBLOCK_L1		MB_VAC350_ADDRESS_L1    //CALIB. BLOCK FOR LOADER 1

// Calibration block for loader 2
#define   MB_VAC350_CALBLOCK_L2			18    //CALIB. BLOCK FOR LOADER 2

#define   MB_VAC350_ADDRESS_L2               MB_VAC350_CALBLOCK_L2 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L2                MB_VAC350_CALBLOCK_L2 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L2               	MB_VAC350_CALBLOCK_L2 + MB_ID_OFFSET	// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L2               	MB_VAC350_CALBLOCK_L2 + MB_ID_OFFSET+1	// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L2              MB_VAC350_CALBLOCK_L2 + MB_PRIORITY_OFFSET	// PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L2           MB_VAC350_CALBLOCK_L2 + MB_SUCTIONTIME_OFFSET	// SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L2               MB_VAC350_CALBLOCK_L2 + MB_PREPOST_OFFSET	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L2                 MB_VAC350_CALBLOCK_L2 + MB_SPARE_OFFSET	// SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 3
#define   MB_VAC350_CALBLOCK_L3			26    //CALIB. BLOCK FOR LOADER 3

#define   MB_VAC350_ADDRESS_L3               MB_VAC350_CALBLOCK_L3 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L3                MB_VAC350_CALBLOCK_L3 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L3               	MB_VAC350_CALBLOCK_L3 + MB_ID_OFFSET	// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L3               	MB_VAC350_CALBLOCK_L3 + MB_ID_OFFSET+1	// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L3              MB_VAC350_CALBLOCK_L3 + MB_PRIORITY_OFFSET	// PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L3           MB_VAC350_CALBLOCK_L3 + MB_SUCTIONTIME_OFFSET	// SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L3               MB_VAC350_CALBLOCK_L3 + MB_PREPOST_OFFSET	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L3                 MB_VAC350_CALBLOCK_L3 + MB_SPARE_OFFSET	// SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 4
#define   MB_VAC350_CALBLOCK_L4			34    //CALIB. BLOCK FOR LOADER 4

#define   MB_VAC350_ADDRESS_L4               MB_VAC350_CALBLOCK_L4 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L4                MB_VAC350_CALBLOCK_L4 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L4               	MB_VAC350_CALBLOCK_L4 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L4               	MB_VAC350_CALBLOCK_L4 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L4              MB_VAC350_CALBLOCK_L4 + MB_PRIORITY_OFFSET	// PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L4           MB_VAC350_CALBLOCK_L4 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L4               MB_VAC350_CALBLOCK_L4 + MB_PREPOST_OFFSET	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L4                 MB_VAC350_CALBLOCK_L4 + MB_SPARE_OFFSET		// SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 5
#define   MB_VAC350_CALBLOCK_L5			42    //CALIB. BLOCK FOR LOADER 5

#define   MB_VAC350_ADDRESS_L5               MB_VAC350_CALBLOCK_L5 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L5                MB_VAC350_CALBLOCK_L5 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L5               	MB_VAC350_CALBLOCK_L5 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L5               	MB_VAC350_CALBLOCK_L5 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L5              MB_VAC350_CALBLOCK_L5 + MB_PRIORITY_OFFSET	// PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L5           MB_VAC350_CALBLOCK_L5 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L5               MB_VAC350_CALBLOCK_L5 + MB_PREPOST_OFFSET	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L5                 MB_VAC350_CALBLOCK_L5 + MB_SPARE_OFFSET		// SPARE REGISTER FOR THIS LOADER


// Calibration block for loader 6
#define   MB_VAC350_CALBLOCK_L6			50    //CALIB. BLOCK FOR LOADER 6

#define   MB_VAC350_ADDRESS_L6               MB_VAC350_CALBLOCK_L6 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L6                MB_VAC350_CALBLOCK_L6 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L6               	MB_VAC350_CALBLOCK_L6 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L6               	MB_VAC350_CALBLOCK_L6 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L6              MB_VAC350_CALBLOCK_L6 + MB_PRIORITY_OFFSET	// PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L6           MB_VAC350_CALBLOCK_L6 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L6               MB_VAC350_CALBLOCK_L6 + MB_PREPOST_OFFSET	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L6                 MB_VAC350_CALBLOCK_L6 + MB_SPARE_OFFSET		// SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 7
#define   MB_VAC350_CALBLOCK_L7			58    //CALIB. BLOCK FOR LOADER 7

#define   MB_VAC350_ADDRESS_L7               MB_VAC350_CALBLOCK_L7 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L7                MB_VAC350_CALBLOCK_L7 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L7               	MB_VAC350_CALBLOCK_L7 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L7               	MB_VAC350_CALBLOCK_L7 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L7              MB_VAC350_CALBLOCK_L7 + MB_PRIORITY_OFFSET	// PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L7           MB_VAC350_CALBLOCK_L7 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L7               MB_VAC350_CALBLOCK_L7 + MB_PREPOST_OFFSET	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L7                 MB_VAC350_CALBLOCK_L7 + MB_SPARE_OFFSET		// SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 8
#define   MB_VAC350_CALBLOCK_L8			66    //CALIB. BLOCK FOR LOADER 8

#define   MB_VAC350_ADDRESS_L8               MB_VAC350_CALBLOCK_L8 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L8                MB_VAC350_CALBLOCK_L8 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L8               	MB_VAC350_CALBLOCK_L8 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L8               	MB_VAC350_CALBLOCK_L8 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L8              MB_VAC350_CALBLOCK_L8 + MB_PRIORITY_OFFSET	// PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L8           MB_VAC350_CALBLOCK_L8 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L8               MB_VAC350_CALBLOCK_L8 + MB_PREPOST_OFFSET	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L8                 MB_VAC350_CALBLOCK_L8 + MB_SPARE_OFFSET		// SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 9
#define   MB_VAC350_CALBLOCK_L9			74    //CALIB. BLOCK FOR LOADER 9

#define   MB_VAC350_ADDRESS_L9               MB_VAC350_CALBLOCK_L9 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L9                MB_VAC350_CALBLOCK_L9 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L9               	MB_VAC350_CALBLOCK_L9 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L9               	MB_VAC350_CALBLOCK_L9 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L9              MB_VAC350_CALBLOCK_L9 + MB_PRIORITY_OFFSET	// PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L9           MB_VAC350_CALBLOCK_L9 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L9               MB_VAC350_CALBLOCK_L9 + MB_PREPOST_OFFSET	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L9                 MB_VAC350_CALBLOCK_L9 + MB_SPARE_OFFSET		// SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 10
#define   MB_VAC350_CALBLOCK_L10			82    //CALIB. BLOCK FOR LOADER 10

#define   MB_VAC350_ADDRESS_L10              MB_VAC350_CALBLOCK_L10 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L10               MB_VAC350_CALBLOCK_L10 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L10               	MB_VAC350_CALBLOCK_L10 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L10               	MB_VAC350_CALBLOCK_L10 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L10             MB_VAC350_CALBLOCK_L10 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L10          MB_VAC350_CALBLOCK_L10 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L10              MB_VAC350_CALBLOCK_L10 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L10                MB_VAC350_CALBLOCK_L10 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 11
#define   MB_VAC350_CALBLOCK_L11			90    //CALIB. BLOCK FOR LOADER 11

#define   MB_VAC350_ADDRESS_L11              MB_VAC350_CALBLOCK_L11 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L11               MB_VAC350_CALBLOCK_L11 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L11               	MB_VAC350_CALBLOCK_L11 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L11               	MB_VAC350_CALBLOCK_L11 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L11             MB_VAC350_CALBLOCK_L11 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L11          MB_VAC350_CALBLOCK_L11 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L11              MB_VAC350_CALBLOCK_L11 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L11                MB_VAC350_CALBLOCK_L11 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 12
#define   MB_VAC350_CALBLOCK_L12			98    //CALIB. BLOCK FOR LOADER 12

#define   MB_VAC350_ADDRESS_L12              MB_VAC350_CALBLOCK_L12 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L12               MB_VAC350_CALBLOCK_L12 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L12               	MB_VAC350_CALBLOCK_L12 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L12               	MB_VAC350_CALBLOCK_L12 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L12             MB_VAC350_CALBLOCK_L12 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L12          MB_VAC350_CALBLOCK_L12 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L12              MB_VAC350_CALBLOCK_L12 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L12                MB_VAC350_CALBLOCK_L12 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 13
#define   MB_VAC350_CALBLOCK_L13			106   //CALIB. BLOCK FOR LOADER 13

#define   MB_VAC350_ADDRESS_L13              MB_VAC350_CALBLOCK_L13 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L13               MB_VAC350_CALBLOCK_L13 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L13               	MB_VAC350_CALBLOCK_L13 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L13               	MB_VAC350_CALBLOCK_L13 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L13             MB_VAC350_CALBLOCK_L13 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L13          MB_VAC350_CALBLOCK_L13 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L13              MB_VAC350_CALBLOCK_L13 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L13                MB_VAC350_CALBLOCK_L13 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 14
#define   MB_VAC350_CALBLOCK_L14			114    //CALIB. BLOCK FOR LOADER 14

#define   MB_VAC350_ADDRESS_L14              MB_VAC350_CALBLOCK_L14 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L14               MB_VAC350_CALBLOCK_L14 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L14               	MB_VAC350_CALBLOCK_L14 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L14               	MB_VAC350_CALBLOCK_L14 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L14             MB_VAC350_CALBLOCK_L14 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L14          MB_VAC350_CALBLOCK_L14 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L14              MB_VAC350_CALBLOCK_L14 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L14                MB_VAC350_CALBLOCK_L14 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 15
#define   MB_VAC350_CALBLOCK_L15			122    //CALIB. BLOCK FOR LOADER 15

#define   MB_VAC350_ADDRESS_L15              MB_VAC350_CALBLOCK_L15 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L15               MB_VAC350_CALBLOCK_L15 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L15               	MB_VAC350_CALBLOCK_L15 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L15               	MB_VAC350_CALBLOCK_L15 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L15             MB_VAC350_CALBLOCK_L15 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L15          MB_VAC350_CALBLOCK_L15 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L15              MB_VAC350_CALBLOCK_L15 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L15                MB_VAC350_CALBLOCK_L15 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 16
#define   MB_VAC350_CALBLOCK_L16			130   //CALIB. BLOCK FOR LOADER 16

#define   MB_VAC350_ADDRESS_L16              MB_VAC350_CALBLOCK_L16 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L16               MB_VAC350_CALBLOCK_L16 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L16               	MB_VAC350_CALBLOCK_L16 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L16               	MB_VAC350_CALBLOCK_L16 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L16             MB_VAC350_CALBLOCK_L16 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L16          MB_VAC350_CALBLOCK_L16 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L16              MB_VAC350_CALBLOCK_L16 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L16                MB_VAC350_CALBLOCK_L16 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 17
#define   MB_VAC350_CALBLOCK_L17			138   //CALIB. BLOCK FOR LOADER 17

#define   MB_VAC350_ADDRESS_L17              MB_VAC350_CALBLOCK_L17 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L17               MB_VAC350_CALBLOCK_L17 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L17               	MB_VAC350_CALBLOCK_L17 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L17               	MB_VAC350_CALBLOCK_L17 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L17             MB_VAC350_CALBLOCK_L17 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L17          MB_VAC350_CALBLOCK_L17 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L17              MB_VAC350_CALBLOCK_L17 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L17                MB_VAC350_CALBLOCK_L17 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 18
#define   MB_VAC350_CALBLOCK_L18			146   //CALIB. BLOCK FOR LOADER 18

#define   MB_VAC350_ADDRESS_L18              MB_VAC350_CALBLOCK_L18 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L18               MB_VAC350_CALBLOCK_L18 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L18               	MB_VAC350_CALBLOCK_L18 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L18               	MB_VAC350_CALBLOCK_L18 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L18             MB_VAC350_CALBLOCK_L18 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L18          MB_VAC350_CALBLOCK_L18 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L18              MB_VAC350_CALBLOCK_L18 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L18                MB_VAC350_CALBLOCK_L18 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 19
#define   MB_VAC350_CALBLOCK_L19			154   //CALIB. BLOCK FOR LOADER 19

#define   MB_VAC350_ADDRESS_L19              MB_VAC350_CALBLOCK_L19 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L19               MB_VAC350_CALBLOCK_L19 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L19               	MB_VAC350_CALBLOCK_L19 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L19               	MB_VAC350_CALBLOCK_L19 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L19             MB_VAC350_CALBLOCK_L19 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L19          MB_VAC350_CALBLOCK_L19 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L19              MB_VAC350_CALBLOCK_L19 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L19                MB_VAC350_CALBLOCK_L19 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 20
#define   MB_VAC350_CALBLOCK_L20			162   //CALIB. BLOCK FOR LOADER 20

#define   MB_VAC350_ADDRESS_L20              MB_VAC350_CALBLOCK_L20 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L20               MB_VAC350_CALBLOCK_L20 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L20               	MB_VAC350_CALBLOCK_L20 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L20               	MB_VAC350_CALBLOCK_L20 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L20             MB_VAC350_CALBLOCK_L20 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L20          MB_VAC350_CALBLOCK_L20 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L20              MB_VAC350_CALBLOCK_L20 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L20                MB_VAC350_CALBLOCK_L20 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 21
#define   MB_VAC350_CALBLOCK_L21			170   //CALIB. BLOCK FOR LOADER 21

#define   MB_VAC350_ADDRESS_L21              MB_VAC350_CALBLOCK_L21 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L21               MB_VAC350_CALBLOCK_L21 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L21               	MB_VAC350_CALBLOCK_L21 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L21               	MB_VAC350_CALBLOCK_L21 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L21             MB_VAC350_CALBLOCK_L21 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L21          MB_VAC350_CALBLOCK_L21 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L21              MB_VAC350_CALBLOCK_L21 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L21                MB_VAC350_CALBLOCK_L21 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 22
#define   MB_VAC350_CALBLOCK_L22			178   //CALIB. BLOCK FOR LOADER 22

#define   MB_VAC350_ADDRESS_L22              MB_VAC350_CALBLOCK_L22 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L22               MB_VAC350_CALBLOCK_L22 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L22               	MB_VAC350_CALBLOCK_L22 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L22               	MB_VAC350_CALBLOCK_L22 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L22             MB_VAC350_CALBLOCK_L22 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L22          MB_VAC350_CALBLOCK_L22 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L22              MB_VAC350_CALBLOCK_L22 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L22                MB_VAC350_CALBLOCK_L22 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 23
#define   MB_VAC350_CALBLOCK_L23			186   //CALIB. BLOCK FOR LOADER 23

#define   MB_VAC350_ADDRESS_L23              MB_VAC350_CALBLOCK_L23 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L23               MB_VAC350_CALBLOCK_L23 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L23               	MB_VAC350_CALBLOCK_L23 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L23               	MB_VAC350_CALBLOCK_L23 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L23             MB_VAC350_CALBLOCK_L23 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L23          MB_VAC350_CALBLOCK_L23 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L23              MB_VAC350_CALBLOCK_L23 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L23                MB_VAC350_CALBLOCK_L23 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 24
#define   MB_VAC350_CALBLOCK_L24			194   //CALIB. BLOCK FOR LOADER 24

#define   MB_VAC350_ADDRESS_L24              MB_VAC350_CALBLOCK_L24 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L24               MB_VAC350_CALBLOCK_L24 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L24               	MB_VAC350_CALBLOCK_L24 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L24               	MB_VAC350_CALBLOCK_L24 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L24             MB_VAC350_CALBLOCK_L24 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L24          MB_VAC350_CALBLOCK_L24 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L24              MB_VAC350_CALBLOCK_L24 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L24                MB_VAC350_CALBLOCK_L24 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 25
#define   MB_VAC350_CALBLOCK_L25			202   //CALIB. BLOCK FOR LOADER 25

#define   MB_VAC350_ADDRESS_L25              MB_VAC350_CALBLOCK_L25 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L25               MB_VAC350_CALBLOCK_L25 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L25               	MB_VAC350_CALBLOCK_L25 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L25               	MB_VAC350_CALBLOCK_L25 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L25             MB_VAC350_CALBLOCK_L25 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L25          MB_VAC350_CALBLOCK_L25 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L25              MB_VAC350_CALBLOCK_L25 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L25                MB_VAC350_CALBLOCK_L25 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 26
#define   MB_VAC350_CALBLOCK_L26			210   //CALIB. BLOCK FOR LOADER 26

#define   MB_VAC350_ADDRESS_L26              MB_VAC350_CALBLOCK_L26 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L26               MB_VAC350_CALBLOCK_L26 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L26               	MB_VAC350_CALBLOCK_L26 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L26               	MB_VAC350_CALBLOCK_L26 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L26             MB_VAC350_CALBLOCK_L26 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L26          MB_VAC350_CALBLOCK_L26 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L26              MB_VAC350_CALBLOCK_L26 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L26                MB_VAC350_CALBLOCK_L26 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 27
#define   MB_VAC350_CALBLOCK_L27			218   //CALIB. BLOCK FOR LOADER 27

#define   MB_VAC350_ADDRESS_L27              MB_VAC350_CALBLOCK_L27 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L27               MB_VAC350_CALBLOCK_L27 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L27               	MB_VAC350_CALBLOCK_L27 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L27               	MB_VAC350_CALBLOCK_L27 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L27             MB_VAC350_CALBLOCK_L27 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L27          MB_VAC350_CALBLOCK_L27 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L27              MB_VAC350_CALBLOCK_L27 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L27                MB_VAC350_CALBLOCK_L27 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 28
#define   MB_VAC350_CALBLOCK_L28			226   //CALIB. BLOCK FOR LOADER 28

#define   MB_VAC350_ADDRESS_L28              MB_VAC350_CALBLOCK_L28 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L28               MB_VAC350_CALBLOCK_L28 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L28               	MB_VAC350_CALBLOCK_L28 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L28               	MB_VAC350_CALBLOCK_L28 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L28             MB_VAC350_CALBLOCK_L28 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L28          MB_VAC350_CALBLOCK_L28 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L28              MB_VAC350_CALBLOCK_L28 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L28                MB_VAC350_CALBLOCK_L28 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 29
#define   MB_VAC350_CALBLOCK_L29			234   //CALIB. BLOCK FOR LOADER 29

#define   MB_VAC350_ADDRESS_L29              MB_VAC350_CALBLOCK_L29 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L29               MB_VAC350_CALBLOCK_L29 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L29               	MB_VAC350_CALBLOCK_L29 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L29               	MB_VAC350_CALBLOCK_L29 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L29             MB_VAC350_CALBLOCK_L29 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L29          MB_VAC350_CALBLOCK_L29 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L29              MB_VAC350_CALBLOCK_L29 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L29                MB_VAC350_CALBLOCK_L29 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 30
#define   MB_VAC350_CALBLOCK_L30			242   //CALIB. BLOCK FOR LOADER 30

#define   MB_VAC350_ADDRESS_L30              MB_VAC350_CALBLOCK_L30 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L30               MB_VAC350_CALBLOCK_L30 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L30               	MB_VAC350_CALBLOCK_L30 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L30               	MB_VAC350_CALBLOCK_L30 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L30             MB_VAC350_CALBLOCK_L30 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L30          MB_VAC350_CALBLOCK_L30 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L30              MB_VAC350_CALBLOCK_L30 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L30                MB_VAC350_CALBLOCK_L30 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 31
#define   MB_VAC350_CALBLOCK_L31			250   //CALIB. BLOCK FOR LOADER 31

#define   MB_VAC350_ADDRESS_L31              MB_VAC350_CALBLOCK_L31 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L31               MB_VAC350_CALBLOCK_L31 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L31               	MB_VAC350_CALBLOCK_L31 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L31               	MB_VAC350_CALBLOCK_L31 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L31             MB_VAC350_CALBLOCK_L31 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L31          MB_VAC350_CALBLOCK_L31 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L31              MB_VAC350_CALBLOCK_L31 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L31                MB_VAC350_CALBLOCK_L31 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER

// Calibration block for loader 32
#define   MB_VAC350_CALBLOCK_L32			258   //CALIB. BLOCK FOR LOADER 32

#define   MB_VAC350_ADDRESS_L32              MB_VAC350_CALBLOCK_L32 + MB_ADDRESS_OFFSET
#define   MB_VAC350_PUMPNO_L32               MB_VAC350_CALBLOCK_L32 + MB_PUMPNO_OFFSET	// NO. OF PUMP FOR THIS LOADER
#define   MB_VAC350_ID_L32               	MB_VAC350_CALBLOCK_L32 + MB_ID_OFFSET		// ID FOR THIS LOADER
#define   MB_VAC350_IDLSW_L32               	MB_VAC350_CALBLOCK_L32 + MB_ID_OFFSET+1		// ID L.S.WORD FOR THIS LOADER
#define   MB_VAC350_PRIORITY_L32             MB_VAC350_CALBLOCK_L32 + MB_PRIORITY_OFFSET  // PRIORITY(1-7) FOR THIS LOADER
#define   MB_VAC350_SUCTIONTIME_L32          MB_VAC350_CALBLOCK_L32 + MB_SUCTIONTIME_OFFSET // SUCTION TIME SECS (MAX 255) FOR THIS LOADER
#define   MB_VAC350_PREPOST_L32              MB_VAC350_CALBLOCK_L32 + MB_PREPOST_OFFSET  	// PRE-POST FILL TIMES FOR THIS LOADER
#define   MB_VAC350_SPARE_L32                MB_VAC350_CALBLOCK_L32 + MB_SPARE_OFFSET     // SPARE REGISTER FOR THIS LOADER


//        *********** PRODUCTION SUMMARY ***************
// COMMON DATA
#define   MB_VAC350_OPSTATUS              266	// OPERATIONAL STATUS
#define   MB_VAC350_SYSALARM              267	// SYSTEM ALARM 
#define   MB_VAC350_PROCALARM             268	// PROCESS ALARM 
#define   MB_VAC350_PROSUMSPAR1           269	// SPARE COMMON DATA

// INDIVIDUAL LOADER DATA
#define   MB_VAC350_PSBLOCKSIZE		  16     //PRODUCTION SUMMARY BLOCK SIZE IN WORDS

// OFFSETS INTO PS BLOCK
// OFFSETS INTO PS BLOCK

#define   MB_STATUS_OFFSET		0
#define   MB_FTIMER_OFFSET		1
#define   MB_OPSTATUS_OFFSET		2
#define   MB_IPSTATUS_OFFSET		3
#define   MB_UNUSEDREAD1_OFFSET	4
#define   MB_ALARM_OFFSET		5
#define   MB_TXCOUNTER_OFFSET		6
#define   MB_RXCOUNTER_OFFSET		7
#define   MB_TOCOUNTER_OFFSET		8
#define   MB_ERRORS_OFFSET		9
#define   MB_COMMAND1_OFFSET		10
#define   MB_COMMAND2_OFFSET		11
#define   MB_COMMAND3_OFFSET		12
#define   MB_PREVGOODRXCOUNTER_OFFSET	13
#define   MB_DUMPDELAY_OFFSET	14
#define   MB_PSSPARE_OFFSET	15

//

#define   MB_VAC350_PSBLOCK_L1 		  278     //PRODUCTION SUMMARY BLOCK FOR LOADER 1
#define   MB_VAC350_STATUS_L1 		  MB_VAC350_PSBLOCK_L1 + MB_STATUS_OFFSET     //STATUS FOR THIS LOADER 
#define   MB_VAC350_IPSTATUS_L1 		  MB_VAC350_PSBLOCK_L1 + MB_IPSTATUS_OFFSET   //IP's STATUS FOR LOADER 
#define   MB_VAC350_OPSTATUS_L1 		  MB_VAC350_PSBLOCK_L1 + MB_OPSTATUS_OFFSET   //OP's STATUS FOR LOADER
#define   MB_VAC350_UNUSEDREAD1_L1 	  MB_VAC350_PSBLOCK_L1 + MB_UNUSEDREAD1_OFFSET //UNUSED READ PARAMETER FOR LOADER
#define   MB_VAC350_ALARM_L1 		  	  MB_VAC350_PSBLOCK_L1 + MB_ALARM_OFFSET   	//ALARM FOR LOADER
#define   MB_VAC350_TXCOUNTER_L1 		  MB_VAC350_PSBLOCK_L1 + MB_TXCOUNTER_OFFSET   //Tx COUNTER FOR LOADER
#define   MB_VAC350_RXCOUNTER_L1 		  MB_VAC350_PSBLOCK_L1 + MB_RXCOUNTER_OFFSET   //Rx COUNTER FOR LOADER
#define   MB_VAC350_TOCOUNTER_L1 		  MB_VAC350_PSBLOCK_L1 + MB_TOCOUNTER_OFFSET   //Time-Out COUNTER FOR LOADER
#define   MB_VAC350_COMMAND1_L1 		  MB_VAC350_PSBLOCK_L1 + MB_COMMAND1_OFFSET   //COMMAND #1 FOR LOADER
#define   MB_VAC350_COMMAND2_L1 		  MB_VAC350_PSBLOCK_L1 + MB_COMMAND2_OFFSET   //COMMAND #2 FOR LOADER
#define   MB_VAC350_COMMAND3_L1 		  MB_VAC350_PSBLOCK_L1 + MB_COMMAND3_OFFSET   //COMMAND #3 FOR LOADER
#define   MB_VAC350_PREVGOODRXCOUNTER_L1  MB_VAC350_PSBLOCK_L1 + MB_PREVGOODRXCOUNTER_OFFSET   //PREV GOOD Rx COUNTER FOR LOADER
#define   MB_VAC350_DUMPDELAY_L1 		  MB_VAC350_PSBLOCK_L1 + MB_DUMPDELAY_OFFSET   //DUMP DELAY FOR LOADER
#define   MB_VAC350_PSSPARE_L1 		  MB_VAC350_PSBLOCK_L1 + MB_PSSPARE_OFFSET   //PROD. SUMM. SPARE FOR LOADER

#define   MB_VAC350_PSBLOCK_L2 		  294     //PRODUCTION SUMMARY BLOCK FOR LOADER 2
#define   MB_VAC350_PSBLOCK_L3 		  310     //PRODUCTION SUMMARY BLOCK FOR LOADER 3
#define   MB_VAC350_PSBLOCK_L4 		  326     //PRODUCTION SUMMARY BLOCK FOR LOADER 4
#define   MB_VAC350_PSBLOCK_L5 		  342     //PRODUCTION SUMMARY BLOCK FOR LOADER 5
#define   MB_VAC350_PSBLOCK_L6 		  358     //PRODUCTION SUMMARY BLOCK FOR LOADER 6
#define   MB_VAC350_PSBLOCK_L7 		  374     //PRODUCTION SUMMARY BLOCK FOR LOADER 7
#define   MB_VAC350_PSBLOCK_L8 		  390     //PRODUCTION SUMMARY BLOCK FOR LOADER 8
#define   MB_VAC350_PSBLOCK_L9 		  406     //PRODUCTION SUMMARY BLOCK FOR LOADER 9

#define   MB_VAC350_PSBLOCK_L10		  422     //PRODUCTION SUMMARY BLOCK FOR LOADER 10
#define   MB_VAC350_PSBLOCK_L11 		  438     //PRODUCTION SUMMARY BLOCK FOR LOADER 11
#define   MB_VAC350_PSBLOCK_L12 		  454     //PRODUCTION SUMMARY BLOCK FOR LOADER 12
#define   MB_VAC350_PSBLOCK_L13 		  470     //PRODUCTION SUMMARY BLOCK FOR LOADER 13
#define   MB_VAC350_PSBLOCK_L14 		  486     //PRODUCTION SUMMARY BLOCK FOR LOADER 14
#define   MB_VAC350_PSBLOCK_L15 		  502     //PRODUCTION SUMMARY BLOCK FOR LOADER 15
#define   MB_VAC350_PSBLOCK_L16 		  518     //PRODUCTION SUMMARY BLOCK FOR LOADER 16
#define   MB_VAC350_PSBLOCK_L17 		  534     //PRODUCTION SUMMARY BLOCK FOR LOADER 17
#define   MB_VAC350_PSBLOCK_L18 		  550     //PRODUCTION SUMMARY BLOCK FOR LOADER 18
#define   MB_VAC350_PSBLOCK_L19 		  566     //PRODUCTION SUMMARY BLOCK FOR LOADER 19

#define   MB_VAC350_PSBLOCK_L20		  582     //PRODUCTION SUMMARY BLOCK FOR LOADER 20
#define   MB_VAC350_PSBLOCK_L21 		  598     //PRODUCTION SUMMARY BLOCK FOR LOADER 21
#define   MB_VAC350_PSBLOCK_L22 		  614     //PRODUCTION SUMMARY BLOCK FOR LOADER 22
#define   MB_VAC350_PSBLOCK_L23 		  630     //PRODUCTION SUMMARY BLOCK FOR LOADER 23
#define   MB_VAC350_PSBLOCK_L24 		  646     //PRODUCTION SUMMARY BLOCK FOR LOADER 24
#define   MB_VAC350_PSBLOCK_L25 		  662     //PRODUCTION SUMMARY BLOCK FOR LOADER 25
#define   MB_VAC350_PSBLOCK_L26 		  678     //PRODUCTION SUMMARY BLOCK FOR LOADER 26
#define   MB_VAC350_PSBLOCK_L27 		  694     //PRODUCTION SUMMARY BLOCK FOR LOADER 27
#define   MB_VAC350_PSBLOCK_L28 		  710     //PRODUCTION SUMMARY BLOCK FOR LOADER 28
#define   MB_VAC350_PSBLOCK_L29 		  726     //PRODUCTION SUMMARY BLOCK FOR LOADER 29

#define   MB_VAC350_PSBLOCK_L30		  742     //PRODUCTION SUMMARY BLOCK FOR LOADER 30
#define   MB_VAC350_PSBLOCK_L31 		  758     //PRODUCTION SUMMARY BLOCK FOR LOADER 31
#define   MB_VAC350_PSBLOCK_L32 		  774     //PRODUCTION SUMMARY BLOCK FOR LOADER 32

